/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_smackem_zlang_interpret_Zln */

#ifndef _Included_net_smackem_zlang_interpret_Zln
#define _Included_net_smackem_zlang_interpret_Zln
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_smackem_zlang_interpret_Zln
 * Method:    executeProgram
 * Signature: (Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_smackem_zlang_interpret_Zln_executeProgram
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
